"""empty message

Revision ID: 094d71f3c335
Revises: 13b0cbd36555
Create Date: 2025-06-06 09:02:39.030149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094d71f3c335'
down_revision = '13b0cbd36555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_transaction_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('external_transaction_id')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
