"""updated game flow

Revision ID: 13b0cbd36555
Revises: 2b3e0e0efadd
Create Date: 2025-06-02 11:49:47.560116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b0cbd36555'
down_revision = '2b3e0e0efadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('platform_fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('white_bet_txn_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('black_bet_txn_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('payout_txn_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('payout_txn_id')
        batch_op.drop_column('black_bet_txn_id')
        batch_op.drop_column('white_bet_txn_id')
        batch_op.drop_column('platform_fee')
        batch_op.drop_column('bet_locked')

    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
